# Generated by Django 4.2.6 on 2023-11-01 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_role", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="userModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uname", models.CharField(max_length=255)),
                ("user_first_name", models.CharField(max_length=50)),
                ("user_last_name", models.CharField(max_length=50)),
                ("user_email", models.CharField(max_length=255)),
                (
                    "user_profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("password", models.CharField(max_length=100)),
                ("verification_code", models.CharField(max_length=35)),
                ("verified", models.BooleanField(default=False)),
                (
                    "user_roleID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_role.roletable",
                    ),
                ),
            ],
        ),
    ]
